package models.details

data class UserContractDetails(
    val agentcompany: Any,
    val agentemail: Any,
    val agentname: Any,
    val agentphone: Any,
    val brand: Any,
    val businessunit: String,
    val clientadiseddate: Any,
    val clientliaison: String,
    val clienttitle: String,
    val constructionliaison: String,
    val contactagent: Boolean,
    val contactemail: String,
    val contactname: String,
    val contactphone: String,
    val contractType: String,
    val contractvalue: String?= null,
    val directions: Any,
    val facade: String? = null,
    val handoverdate: Any,
    val homephone: String,
    val homephone1: String,
    val homephone2: Any,
    val housetype: String? = null,
    val id: Int,
    val job: String,
    val jobstatus: String,
    val jobstatuscode: String,
    val lotaddress: String,
    val lotlevelno: Any,
    val lotno: Any,
    val lotpostcode: Any,
    val lotstate: Any,
    val lotstreet1: Any,
    val lotstreet2: Any,
    val lotstreetno: Any,
    val lotsuburb: String,
    val lotunitno: Any,
    val salesContact: SalesContact,
    val salesperson: String,
    val sitestartdate: Any,
    val supervisor: String,
    val surname: String,
    val workphone: String,
    val workphone1: String,
    val workphone2: Any
)